version: "3"
services:
  app:
    build: .
    volumes:
      - ./downloads:/downloads
    depends_on:
      - rs
    command: sh -c "python main.py"
#    command: sh -c "python test.py"

  rs:
    image: redis
    ports:
      - "6379:6379"